/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emansi;

import javax.swing.JOptionPane;

/**
 *
 * @author acek
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    private koneksi connection = new koneksi();
    private session usr = new session();

    public home() {
        initComponents();
    }

    public void setNama(String nama) {
        Lnama.setText(nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExit = new javax.swing.JButton();
        jReg = new javax.swing.JButton();
        jEvent = new javax.swing.JButton();
        jDetail = new javax.swing.JButton();
        jSearch = new javax.swing.JButton();
        jvery = new javax.swing.JButton();
        jLogout = new javax.swing.JButton();
        Lnama = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backgroun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jExit.setBorderPainted(false);
        jExit.setContentAreaFilled(false);
        jExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit1.png"))); // NOI18N
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/r.png"))); // NOI18N
        jReg.setBorderPainted(false);
        jReg.setContentAreaFilled(false);
        jReg.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/r2.png"))); // NOI18N
        jReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegActionPerformed(evt);
            }
        });
        getContentPane().add(jReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 210, 210));

        jEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/e.png"))); // NOI18N
        jEvent.setToolTipText("");
        jEvent.setBorderPainted(false);
        jEvent.setContentAreaFilled(false);
        jEvent.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/e2.png"))); // NOI18N
        jEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEventActionPerformed(evt);
            }
        });
        getContentPane().add(jEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 210, 210));

        jDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/d.png"))); // NOI18N
        jDetail.setBorderPainted(false);
        jDetail.setContentAreaFilled(false);
        jDetail.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/d2.png"))); // NOI18N
        jDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDetailActionPerformed(evt);
            }
        });
        getContentPane().add(jDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 210, 210));

        jSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/s.png"))); // NOI18N
        jSearch.setBorderPainted(false);
        jSearch.setContentAreaFilled(false);
        jSearch.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/s2.png"))); // NOI18N
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 100, 100));

        jvery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/l.png"))); // NOI18N
        jvery.setBorderPainted(false);
        jvery.setContentAreaFilled(false);
        jvery.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/l2.png"))); // NOI18N
        jvery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jveryActionPerformed(evt);
            }
        });
        getContentPane().add(jvery, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 100, 100));

        jLogout.setBackground(new java.awt.Color(0, 51, 51));
        jLogout.setFont(new java.awt.Font("Aroania", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(204, 204, 255));
        jLogout.setText("Logout");
        jLogout.setBorderPainted(false);
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        Lnama.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        Lnama.setForeground(new java.awt.Color(204, 204, 204));
        Lnama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lnama.setText("...");
        getContentPane().add(Lnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 130, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 40, 30));

        backgroun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background1.png"))); // NOI18N
        getContentPane().add(backgroun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        int a = JOptionPane.showConfirmDialog(rootPane, "Clik Yes to exit", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jExitActionPerformed

    private void jRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegActionPerformed
        // TODO add your handling code here:
         if (usr.get().equals("U06")) {
            JOptionPane.showMessageDialog(rootPane, "can't Access!", "ERROR", JOptionPane.ERROR_MESSAGE);
         } else {
        dispose();
        new vregistration().setVisible(true);
         }
    }//GEN-LAST:event_jRegActionPerformed

    private void jveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jveryActionPerformed
        // TODO add your handling code here:
          if (usr.get().equals("U06")) {
            JOptionPane.showMessageDialog(rootPane, "can't Access!", "ERROR", JOptionPane.ERROR_MESSAGE);
         } else {
        dispose();
        new vverification().setVisible(true);
         }
        
    }//GEN-LAST:event_jveryActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
            if (usr.get().equals("U06")) {
            JOptionPane.showMessageDialog(rootPane, "can't Access!", "ERROR", JOptionPane.ERROR_MESSAGE);
         } else {
        dispose();
        new vsearch().setVisible(true);
         }
       
    }//GEN-LAST:event_jSearchActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDetailActionPerformed
        // TODO add your handling code here:
  if (usr.get().equals("U06")) {
            JOptionPane.showMessageDialog(rootPane, "can't Access!", "ERROR", JOptionPane.ERROR_MESSAGE);
         } else {
        dispose();
        new vdetail().setVisible(true);
         }
    }//GEN-LAST:event_jDetailActionPerformed

    private void jEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEventActionPerformed
        if (usr.get().equals("U06")) {
            dispose();
            new vevent().setVisible(true);
           
            } else {
             int a = JOptionPane.showConfirmDialog(rootPane, "Can't Access!\nPlease"
                    + "login as administrator\n"
                    + "clik Yes to login", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (a == 0) {
                dispose();
                new login().setVisible(true);
            }
        }
    }//GEN-LAST:event_jEventActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Aplikasi ini digunakan untuk\n"
                + "memudahkan dalam memanajemen acara\n"
                + "yang ada di Program Studi Sistem Informasi\n"
                + "UNIVERSITAS JEMBER");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel backgroun;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jDetail;
    private javax.swing.JButton jEvent;
    private javax.swing.JButton jExit;
    private javax.swing.JButton jLogout;
    private javax.swing.JButton jReg;
    private javax.swing.JButton jSearch;
    private javax.swing.JButton jvery;
    // End of variables declaration//GEN-END:variables
}
