/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emansi;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acek
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    private koneksi connection = new koneksi();
    private session usr = new session();

    public report() {
        initComponents();
        cbAcara.addItem("Pendaftaran");
        cbAcara.addItem("Acara");

    }

    public void pilih(String pilihan) {
        switch (pilihan) {
            case "Pendaftaran":
                showPendaftaran();
                break;
            case "Acara":
                showAcara();
                break;
            default:
                throw new AssertionError();
        }
    }

    public void showPendaftaran() {
        String query = "select d.nama, d.Instansi, d.Alamat, "
                + "d.NO_HP, d.Tanggal, e.nama_event, l.username as Penyelenggara "
                + "from data d join Event e on "
                + "d.id_event = e.id_event "
                + "join jenis j on d.id_jenis = j.id_jenis "
                + "join login l on e.id_user = l.id_user "
                + "where e.id_user = '" + usr.get() + "' and d.id_jenis = 1";
        DefaultTableModel model = connection.select(query);
        tbReport.setModel(model);
    }

    public void showAcara() {
        String query = "select e.nama_event, e.jenis_acara, "
                + "e.tanggal_acara, e.tempat, pemateri, e.awal_pendaftaran,"
                + " e.akhir_pendaftaran, l.username as Penyelenggara "
                + "from Event e join login l on e.id_user = l.id_user "
                + "where e.id_user ='" + usr.get() + "'";
        DefaultTableModel model = connection.select(query);
        tbReport.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAcara = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReport = new javax.swing.JTable();
        jcetak = new javax.swing.JButton();
        jBack = new javax.swing.JButton();
        jLogout = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbAcara.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        cbAcara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAcaraActionPerformed(evt);
            }
        });
        getContentPane().add(cbAcara, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 220, -1));

        tbReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbReport);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 880, 390));

        jcetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print.png"))); // NOI18N
        jcetak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcetak.setDefaultCapable(false);
        jcetak.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print1.png"))); // NOI18N
        jcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcetakActionPerformed(evt);
            }
        });
        getContentPane().add(jcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 60, 60));

        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jBack.setBorderPainted(false);
        jBack.setContentAreaFilled(false);
        jBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back1.png"))); // NOI18N
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 50));

        jLogout.setBackground(new java.awt.Color(0, 51, 51));
        jLogout.setFont(new java.awt.Font("Aroania", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(204, 204, 255));
        jLogout.setText("Logout");
        jLogout.setBorderPainted(false);
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jExit.setBorderPainted(false);
        jExit.setContentAreaFilled(false);
        jExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit1.png"))); // NOI18N
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background7.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbAcaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAcaraActionPerformed
        pilih(cbAcara.getSelectedItem().toString());
    }//GEN-LAST:event_cbAcaraActionPerformed

    private void jcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcetakActionPerformed
        new cetak().cetak(tbReport);
    }//GEN-LAST:event_jcetakActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_jBackActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        int a = JOptionPane.showConfirmDialog(rootPane, "Clik Yes to exit", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Aplikasi ini digunakan untuk\n"
            + "memudahkan dalam memanajemen acara\n"
            + "yang ada di Program Studi Sistem Informasi\n"
            + "UNIVERSITAS JEMBER");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAcara;
    private javax.swing.JButton jBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jcetak;
    private javax.swing.JTable tbReport;
    // End of variables declaration//GEN-END:variables
}
