/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emansi;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acek
 */
public class vdetail extends javax.swing.JFrame {

    /**
     * Creates new form vdetail
     */
    private koneksi connection = new koneksi();
    private session usr = new session();

    public vdetail() {
        initComponents();
        Status();
        getAcara();
        ShowLabel();
    }

    public void ShowLabel() {
        setPenyelenggara();
        setDetail("nama_event", nama);
        setDetail("Jenis_Acara", Ljenis);
        setDetail("Tanggal_Acara", LTgl);
        setDetail("Tempat", Ltempat);
        setDetail("Pemateri", Lpemateri);
        setDetail("Awal_Pendaftaran", Lawal);
        setDetail("Akhir_Pendaftaran", Lakhir);
        setTotal();
    }

    public void setPenyelenggara() {
        String opsiAcara = cbAcara.getSelectedItem().toString();
        int id = connection.getID(opsiAcara);
        try {
            Statement st = connection.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery("select l.username from Event e "
                    + "join login l on e.id_user = l.id_user "
                    + "where e.id_event = " + id);
            rs.next();
            Lpenyelenggara.setText(rs.getString(1));
        } catch (SQLException e) {
            System.out.println("" + e);
        }
    }

    public void setDetail(String isi, JLabel label) {
        String opsiAcara = cbAcara.getSelectedItem().toString();
        int id = connection.getID(opsiAcara);
        System.out.println(opsiAcara);
        try {
            Statement st = connection.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery("SELECT " + isi + " from Event "
                    + "where id_event = " + id);
            rs.next();
            label.setText(rs.getString(1));
        } catch (SQLException e) {
            System.out.println("" + e);
        }
    }
    
    public void setTotal() {
        String opsiAcara = cbAcara.getSelectedItem().toString();
        int id = connection.getID(opsiAcara);
        try {
            Statement st = connection.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery("select e.nama_event, count(*) as Total_Peserta "
                    + "from data d join Event e on d.id_event = e.id_event "
                    + "join login l on e.id_user = l.id_user "
                    + "where e.id_event = "+id +""
                    + " group by e.nama_event");
             rs.last();
             int count = rs.getRow();
             rs.beforeFirst();
             rs.next();
             Ltotal.setText((count > 0)?rs.getString(2):"0");
            
        } catch (SQLException e) {
            System.out.println("" + e);
        }
    }

    public void Status() {
        showStatus("1", dpendaftaran);
        showStatus("2", dpendaftaran1);
    }

    public void showStatus(String status, JTable tabel) {
        String query = "select e.nama_event, count(*) as Total_Peserta "
                + "from data d join Event e "
                + "on d.id_event = e.id_event "
                + "join login l on e.id_user = l.id_user "
                + "where l.id_user = '" + usr.get() + "' and d.id_jenis = '" + status + "' "
                + "group by e.nama_event";
        DefaultTableModel model = connection.select(query);
        tabel.setModel(model);
    }

    public void getAcara() {
        String query = "SELECT * From Event e "
                + "left join login l on e.id_user = l.id_user "
                + "where e.id_user='" + usr.get() + "'";
        String j[] = connection.getData(query, 2);
        for (int i = 0; i < j.length; i++) {
            cbAcara.addItem(j[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExit = new javax.swing.JButton();
        jLogout = new javax.swing.JButton();
        jBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dpendaftaran = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        dpendaftaran1 = new javax.swing.JTable();
        cbAcara = new javax.swing.JComboBox();
        jcheck = new javax.swing.JButton();
        jcek = new javax.swing.JButton();
        jCetak = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ltotal = new javax.swing.JLabel();
        Ljenis = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Lpenyelenggara = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LTgl = new javax.swing.JLabel();
        Ltempat = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Lpemateri = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Lawal = new javax.swing.JLabel();
        Lakhir = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jExit.setBorderPainted(false);
        jExit.setContentAreaFilled(false);
        jExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit1.png"))); // NOI18N
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLogout.setBackground(new java.awt.Color(0, 51, 51));
        jLogout.setFont(new java.awt.Font("Aroania", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(204, 204, 255));
        jLogout.setText("Logout");
        jLogout.setBorderPainted(false);
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jBack.setBorderPainted(false);
        jBack.setContentAreaFilled(false);
        jBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back1.png"))); // NOI18N
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 50));

        dpendaftaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(dpendaftaran);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 320, 130));

        dpendaftaran1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(dpendaftaran1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 320, 130));

        cbAcara.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        cbAcara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAcaraActionPerformed(evt);
            }
        });
        getContentPane().add(cbAcara, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, -1));

        jcheck.setText("Detail Acara");
        jcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckActionPerformed(evt);
            }
        });
        getContentPane().add(jcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jcek.setText("Detail");
        jcek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcekActionPerformed(evt);
            }
        });
        getContentPane().add(jcek, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, -1, -1));

        jCetak.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCetak.setText("REPORT");
        jCetak.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCetak.setContentAreaFilled(false);
        jCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 150, 50));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Detail Acara");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 185, -1, 20));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Pendaftar yang belum melunasi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Pendaftar yang telah melunasi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        nama.setForeground(new java.awt.Color(204, 204, 204));
        nama.setText("nama");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 210, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("s/d");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        Ltotal.setForeground(new java.awt.Color(204, 204, 204));
        Ltotal.setText("0");
        getContentPane().add(Ltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 70, -1));

        Ljenis.setForeground(new java.awt.Color(204, 204, 204));
        Ljenis.setText("jenis");
        getContentPane().add(Ljenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 210, -1));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Jenis Acara");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        Lpenyelenggara.setForeground(new java.awt.Color(204, 204, 204));
        Lpenyelenggara.setText("Penyelenggara");
        getContentPane().add(Lpenyelenggara, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 210, -1));

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Penyelenggara");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        LTgl.setForeground(new java.awt.Color(204, 204, 204));
        LTgl.setText("tanggal");
        getContentPane().add(LTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 210, -1));

        Ltempat.setForeground(new java.awt.Color(204, 204, 204));
        Ltempat.setText("tempat");
        getContentPane().add(Ltempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 210, -1));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Tanggal Acara");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Tempat");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        Lpemateri.setForeground(new java.awt.Color(204, 204, 204));
        Lpemateri.setText("pemateri");
        getContentPane().add(Lpemateri, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 210, -1));

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Pemateri");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        Lawal.setForeground(new java.awt.Color(204, 204, 204));
        Lawal.setText("awal");
        getContentPane().add(Lawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 110, -1));

        Lakhir.setForeground(new java.awt.Color(204, 204, 204));
        Lakhir.setText("akhir");
        getContentPane().add(Lakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 120, -1));

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Pendaftaran");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Nama Acara");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Total Peserta");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        int a = JOptionPane.showConfirmDialog(rootPane, "Clik Yes to exit", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jExitActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_jBackActionPerformed

    private void cbAcaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAcaraActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_cbAcaraActionPerformed

    private void jcekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcekActionPerformed
        // TODO add your handling code here:
        new vlist().setVisible(true);
    }//GEN-LAST:event_jcekActionPerformed

    private void jcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckActionPerformed
        // TODO add your handling code here:
        ShowLabel();
    }//GEN-LAST:event_jcheckActionPerformed

    private void jCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCetakActionPerformed
        // TODO add your handling code here:
        dispose();
        new report().setVisible(true);
    }//GEN-LAST:event_jCetakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Aplikasi ini digunakan untuk\n"
            + "memudahkan dalam memanajemen acara\n"
            + "yang ada di Program Studi Sistem Informasi\n"
            + "UNIVERSITAS JEMBER");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vdetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LTgl;
    private javax.swing.JLabel Lakhir;
    private javax.swing.JLabel Lawal;
    private javax.swing.JLabel Ljenis;
    private javax.swing.JLabel Lpemateri;
    private javax.swing.JLabel Lpenyelenggara;
    private javax.swing.JLabel Ltempat;
    private javax.swing.JLabel Ltotal;
    private javax.swing.JComboBox cbAcara;
    private javax.swing.JTable dpendaftaran;
    private javax.swing.JTable dpendaftaran1;
    private javax.swing.JButton jBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCetak;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jcek;
    private javax.swing.JButton jcheck;
    private javax.swing.JLabel nama;
    // End of variables declaration//GEN-END:variables
}
