/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emansi;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acek
 */
public class vevent extends javax.swing.JFrame {

    /**
     * Creates new form vevent
     */
    private koneksi connection = new koneksi();
    private session usr = new session();

    public vevent() {
        initComponents();
        getUser();
        showAcara();
    }

    public void getUser() {
        String j[] = connection.getData("SELECT * from login", 1);
        System.out.println("");
        for (int i = 0; i < j.length - 1; i++) {
            cbUsr.addItem(j[i]);
        }
    }

    public void showAcara() {
        String query = "SELECT id_event,"
                + " nama_event, "
                + " Tanggal_Acara, "
                + " Pemateri, "
                + "Tempat  "
                + "FROM Event "
                + "where id_user='" + cbUsr.getSelectedItem().toString() + "'";
        DefaultTableModel model = connection.select(query);
        addAcara.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogout = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jBack = new javax.swing.JButton();
        tfNew = new javax.swing.JTextField();
        jbAdd = new javax.swing.JButton();
        tfStart = new com.toedter.calendar.JDateChooser();
        tfEnd = new com.toedter.calendar.JDateChooser();
        tfTanggal = new com.toedter.calendar.JDateChooser();
        tfTempat = new javax.swing.JTextField();
        tfAcara = new javax.swing.JTextField();
        tfPemateri = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addAcara = new javax.swing.JTable();
        cbUsr = new javax.swing.JComboBox();
        help = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLogout.setBackground(new java.awt.Color(0, 51, 51));
        jLogout.setFont(new java.awt.Font("Aroania", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(204, 204, 255));
        jLogout.setText("Logout");
        jLogout.setBorderPainted(false);
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jExit.setBorderPainted(false);
        jExit.setContentAreaFilled(false);
        jExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit1.png"))); // NOI18N
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jBack.setBorderPainted(false);
        jBack.setContentAreaFilled(false);
        jBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back1.png"))); // NOI18N
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 50));

        tfNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNewMouseClicked(evt);
            }
        });
        tfNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNewActionPerformed(evt);
            }
        });
        getContentPane().add(tfNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 190, -1));

        jbAdd.setText("Create");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));
        getContentPane().add(tfStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));
        getContentPane().add(tfEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, -1, -1));
        getContentPane().add(tfTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, -1));
        getContentPane().add(tfTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 180, -1));
        getContentPane().add(tfAcara, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 180, -1));
        getContentPane().add(tfPemateri, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 180, -1));

        addAcara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(addAcara);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 590, 340));

        cbUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUsrActionPerformed(evt);
            }
        });
        getContentPane().add(cbUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 210, -1));

        help.setFont(new java.awt.Font("Jamrul", 0, 14)); // NOI18N
        help.setText("?");
        help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        help.setContentAreaFilled(false);
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        getContentPane().add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 30, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("s/d");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Nama Acara");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Tanggal Pendaftaran");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Tanggal Acara");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Tempat Acara");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Pemateri");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Jenis Acara");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        int a = JOptionPane.showConfirmDialog(rootPane, "Clik Yes to exit", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jExitActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_jBackActionPerformed

    private void tfNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNewMouseClicked
        // TODO add your handling code here:
        tfNew.setText("");
    }//GEN-LAST:event_tfNewMouseClicked

    private void tfNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNewActionPerformed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        int a = JOptionPane.showConfirmDialog(rootPane, "Pastikan Data yang anda masukkan"
                + "benar.\nklik Yes untuk menyimpan", "Berhasil", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            String nama = tfNew.getText();
            SimpleDateFormat formatdate;
            formatdate = new SimpleDateFormat("yyyy-M-d");
            String tglStart = formatdate.format(tfStart.getDate());
            String tglEnd = formatdate.format(tfEnd.getDate());
            String tglNow = formatdate.format(tfTanggal.getDate());
            String tempat = tfTempat.getText();
            String pemateri = tfPemateri.getText();
            String acr = tfAcara.getText();
            String user = cbUsr.getSelectedItem().toString();

            String query = "INSERT INTO `siap`.`Event` ("
                    + "id_event, "
                    + "nama_event, "
                    + "Awal_Pendaftaran, "
                    + "Akhir_Pendaftaran, "
                    + "Tanggal_Acara, "
                    + "Tempat, "
                    + "Pemateri, "
                    + "Jenis_Acara, "
                    + "id_user) "
                    + "VALUES "
                    + "(NULL ,  "
                    + "'" + nama + "', "
                    + "'" + tglStart + "', "
                    + "'" + tglEnd + "', "
                    + "'" + tglNow + "', "
                    + "'" + tempat + "', "
                    + "'" + pemateri + "', "
                    + "'" + acr + "', '"
                    + user + "') "
                    + "where DATEDIFF";
            connection.insertUpdateDelete(query);
            showAcara();
            reset();
        }
    }//GEN-LAST:event_jbAddActionPerformed

    private void cbUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUsrActionPerformed
        showAcara();
    }//GEN-LAST:event_cbUsrActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "List user :\n"
                + "U01 -- LAOS\n"
                + "U02 -- ETALASE\n"
                + "U03 -- UKMO\n"
                + "U04 -- BALWANA\n"
                + "U05 -- BITS");
    }//GEN-LAST:event_helpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Aplikasi ini digunakan untuk\n"
            + "memudahkan dalam memanajemen acara\n"
            + "yang ada di Program Studi Sistem Informasi\n"
            + "UNIVERSITAS JEMBER");
    }//GEN-LAST:event_jButton1ActionPerformed

    public void reset() {
        tfAcara.setText("");
        tfTempat.setText("");
        tfPemateri.setText("");
        tfNew.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vevent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable addAcara;
    private javax.swing.JComboBox cbUsr;
    private javax.swing.JButton help;
    private javax.swing.JButton jBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdd;
    private javax.swing.JTextField tfAcara;
    private com.toedter.calendar.JDateChooser tfEnd;
    private javax.swing.JTextField tfNew;
    private javax.swing.JTextField tfPemateri;
    private com.toedter.calendar.JDateChooser tfStart;
    private com.toedter.calendar.JDateChooser tfTanggal;
    private javax.swing.JTextField tfTempat;
    // End of variables declaration//GEN-END:variables
}
