/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emansi;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acek
 */
public class vverification extends javax.swing.JFrame {

    /**
     * Creates new form vverification
     */
    private koneksi connection = new koneksi();
    private session usr = new session();

    public vverification() {
        initComponents();
    }

    private void cekBooking() {
        // TODO add your handling code here:
        String query = "SELECT d.Nomor,"
                + " d.Nama, "
                + "j.Status "
                + "FROM data d join jenis j "
                + "on (j.id_jenis = d.id_jenis) "
                + "join Event e on d.id_event = e.id_event  "
                + " where j.Status = 'Booking' "
                + "and e.id_user='" + usr.get() + "'";
        DefaultTableModel model = connection.select(query);
        jtBooking.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExit = new javax.swing.JButton();
        jLogout = new javax.swing.JButton();
        jBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLunas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtBooking = new javax.swing.JTable();
        verifikasi = new javax.swing.JButton();
        cekLunas = new javax.swing.JButton();
        cekBooking = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jExit.setBorderPainted(false);
        jExit.setContentAreaFilled(false);
        jExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit1.png"))); // NOI18N
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLogout.setBackground(new java.awt.Color(0, 51, 51));
        jLogout.setFont(new java.awt.Font("Aroania", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(204, 204, 255));
        jLogout.setText("Logout");
        jLogout.setBorderPainted(false);
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jBack.setBorderPainted(false);
        jBack.setContentAreaFilled(false);
        jBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back1.png"))); // NOI18N
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 50));

        jtLunas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jtLunas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 400, 270));

        jtBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(jtBooking);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 400, 270));

        verifikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/verifikasi1.png"))); // NOI18N
        verifikasi.setBorderPainted(false);
        verifikasi.setContentAreaFilled(false);
        verifikasi.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/verifikasi.png"))); // NOI18N
        verifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifikasiActionPerformed(evt);
            }
        });
        getContentPane().add(verifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 120, 120));

        cekLunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lunas1.png"))); // NOI18N
        cekLunas.setBorderPainted(false);
        cekLunas.setContentAreaFilled(false);
        cekLunas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lunas.png"))); // NOI18N
        cekLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekLunasActionPerformed(evt);
            }
        });
        getContentPane().add(cekLunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 120, 120));

        cekBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/booking1.png"))); // NOI18N
        cekBooking.setBorderPainted(false);
        cekBooking.setContentAreaFilled(false);
        cekBooking.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/booking.png"))); // NOI18N
        cekBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBookingActionPerformed(evt);
            }
        });
        getContentPane().add(cekBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, 120));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background6.png"))); // NOI18N
        jLabel1.setText("\\");
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 600));

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_jBackActionPerformed

    private void cekLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekLunasActionPerformed
        // TODO add your handling code here:
        ceklunas();
    }//GEN-LAST:event_cekLunasActionPerformed

    private void cekBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBookingActionPerformed
        cekBooking();
    }//GEN-LAST:event_cekBookingActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        int a = JOptionPane.showConfirmDialog(rootPane, "Some input data "
                + "in textfield maybe will lose"
                + "\nClik Yes to confirm", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jExitActionPerformed


    private void verifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifikasiActionPerformed
        // TODO add your handling code here:
        String id = jtBooking.getValueAt(jtBooking.getSelectedRow(), 0).toString();
        String sql = "update data set id_jenis = 1 where nomor = " + id;
        connection.insertUpdateDelete(sql);
        cekBooking();
        ceklunas();
    }//GEN-LAST:event_verifikasiActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Aplikasi ini digunakan untuk\n"
            + "memudahkan dalam memanajemen acara\n"
            + "yang ada di Program Studi Sistem Informasi\n"
            + "UNIVERSITAS JEMBER");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ceklunas() {
        String query = "SELECT d.Nomor,"
                + " d.Nama, "
                + "j.Status "
                + "FROM data d join jenis j "
                + "on (j.id_jenis = d.id_jenis) "
                + "join Event e on d.id_event = e.id_event  "
                + " where j.Status = 'Lunas' "
                + "and e.id_user='" + usr.get() + "'";
        DefaultTableModel model = connection.select(query);
        jtLunas.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vverification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vverification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vverification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vverification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vverification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekBooking;
    private javax.swing.JButton cekLunas;
    private javax.swing.JButton jBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtBooking;
    private javax.swing.JTable jtLunas;
    private javax.swing.JButton verifikasi;
    // End of variables declaration//GEN-END:variables
}
